package org.trd.app.teknichrono.model;
// Generated 5 mai 2016 11:08:49 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Inventory generated by hbm2java
 */
@Entity
@XmlRootElement
public class Inventory implements java.io.Serializable {

	private int id;
	private double timenow;
	private String uuid;
	private int major;
	private int minor;
	private int power;

	public Inventory() {
	}

	public Inventory(int id, double timenow, String uuid, int major, int minor,
			int power) {
		this.id = id;
		this.timenow = timenow;
		this.uuid = uuid;
		this.major = major;
		this.minor = minor;
		this.power = power;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "TIMENOW", nullable = false, precision = 17, scale = 0)
	public double getTimenow() {
		return this.timenow;
	}

	public void setTimenow(double timenow) {
		this.timenow = timenow;
	}

	@Column(name = "UUID", nullable = false)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "MAJOR", nullable = false)
	public int getMajor() {
		return this.major;
	}

	public void setMajor(int major) {
		this.major = major;
	}

	@Column(name = "MINOR", nullable = false)
	public int getMinor() {
		return this.minor;
	}

	public void setMinor(int minor) {
		this.minor = minor;
	}

	@Column(name = "POWER", nullable = false)
	public int getPower() {
		return this.power;
	}

	public void setPower(int power) {
		this.power = power;
	}

}
