package org.trd.app.teknichrono.pi.model;
// Generated 5 mai 2016 11:08:49 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Lap generated by hbm2java
 */
@Entity
@XmlRootElement
public class PiLap implements java.io.Serializable {

	private int id;
	private double timelap;
	private int beacon;

	public PiLap() {
	}

	public PiLap(int id, double timelap, int beacon) {
		this.id = id;
		this.timelap = timelap;
		this.beacon = beacon;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "TIMELAP", nullable = false, precision = 17, scale = 0)
	public double getTimelap() {
		return this.timelap;
	}

	public void setTimelap(double timelap) {
		this.timelap = timelap;
	}

	@Column(name = "BEACON", nullable = false)
	public int getBeacon() {
		return this.beacon;
	}

	public void setBeacon(int beacon) {
		this.beacon = beacon;
	}

}
