package org.trd.app.teknichrono.pi.model;
// Generated 5 mai 2016 11:08:49 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Listing generated by hbm2java
 */
@Entity
@XmlRootElement
public class PiListing implements java.io.Serializable {

	private int id;
	private int commande;
	private int idShop;
	private String nom;
	private String prenom;
	private String moto;
	private String cylindree;
	private String adresse;
	private String telephone;
	private String rc;
	private String indiv;
	private String licence;
	private String emplacement;
	private int beacon;
	private int groupe;
	private String paiement;
	private String valid;

	public PiListing() {
	}

	public PiListing(int id, int commande, int idShop, String nom, String prenom,
			String moto, String cylindree, String adresse, String telephone, String rc,
			String indiv, String licence, String emplacement, int beacon, int groupe,
			String paiement, String valid) {
		this.id = id;
		this.commande = commande;
		this.idShop = idShop;
		this.nom = nom;
		this.prenom = prenom;
		this.moto = moto;
		this.cylindree = cylindree;
		this.adresse = adresse;
		this.telephone = telephone;
		this.rc = rc;
		this.indiv = indiv;
		this.licence = licence;
		this.emplacement = emplacement;
		this.beacon = beacon;
		this.groupe = groupe;
		this.paiement = paiement;
		this.valid = valid;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "COMMANDE", nullable = false)
	public int getCommande() {
		return this.commande;
	}

	public void setCommande(int commande) {
		this.commande = commande;
	}

	@Column(name = "ID_SHOP", nullable = false)
	public int getIdShop() {
		return this.idShop;
	}

	public void setIdShop(int idShop) {
		this.idShop = idShop;
	}

	@Column(name = "NOM", nullable = false)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM", nullable = false)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "MOTO", nullable = false)
	public String getMoto() {
		return this.moto;
	}

	public void setMoto(String moto) {
		this.moto = moto;
	}

	@Column(name = "CYLINDREE", nullable = false)
	public String getCylindree() {
		return this.cylindree;
	}

	public void setCylindree(String cylindree) {
		this.cylindree = cylindree;
	}

	@Column(name = "ADRESSE", nullable = false)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "TELEPHONE", nullable = false)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "RC", nullable = false)
	public String getRc() {
		return this.rc;
	}

	public void setRc(String rc) {
		this.rc = rc;
	}

	@Column(name = "INDIV", nullable = false)
	public String getIndiv() {
		return this.indiv;
	}

	public void setIndiv(String indiv) {
		this.indiv = indiv;
	}

	@Column(name = "LICENCE", nullable = false)
	public String getLicence() {
		return this.licence;
	}

	public void setLicence(String licence) {
		this.licence = licence;
	}

	@Column(name = "EMPLACEMENT", nullable = false)
	public String getEmplacement() {
		return this.emplacement;
	}

	public void setEmplacement(String emplacement) {
		this.emplacement = emplacement;
	}

	@Column(name = "BEACON", nullable = false)
	public int getBeacon() {
		return this.beacon;
	}

	public void setBeacon(int beacon) {
		this.beacon = beacon;
	}

	@Column(name = "GROUPE", nullable = false)
	public int getGroupe() {
		return this.groupe;
	}

	public void setGroupe(int groupe) {
		this.groupe = groupe;
	}

	@Column(name = "PAIEMENT", nullable = false)
	public String getPaiement() {
		return this.paiement;
	}

	public void setPaiement(String paiement) {
		this.paiement = paiement;
	}

	@Column(name = "VALID", nullable = false)
	public String getValid() {
		return this.valid;
	}

	public void setValid(String valid) {
		this.valid = valid;
	}

}
