apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "teknichrono"
    version: "${project.version}"
    group: "fabricepipart"
  name: "teknichrono"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "teknichrono"
      version: "${project.version}"
      group: "fabricepipart"
  template:
    metadata:
      labels:
        app: "teknichrono"
        version: "${project.version}"
        group: "fabricepipart"
    spec:
      containers:
        - env:
            - name: "KUBERNETES_NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-user
                  key: QUARKUS_DATASOURCE_PASSWORD
          image: "fabricepipart/teknichrono-backend:${project.version}"
          imagePullPolicy: "IfNotPresent"
          livenessProbe:
            httpGet:
              path: "/q/health/live"
              port: 8080
              scheme: "HTTP"
            initialDelaySeconds: 0
            periodSeconds: 30
            timeoutSeconds: 10
          name: "teknichrono"
          ports:
            - containerPort: 8080
              name: "http"
              protocol: "TCP"
          readinessProbe:
            httpGet:
              path: "/q/health/ready"
              port: 8080
              scheme: "HTTP"
            initialDelaySeconds: 0
            periodSeconds: 30
            timeoutSeconds: 10
